fix

diff --git a/.github/workflows/maven-snapshot-github-deploy.yaml b/.github/workflows/maven-snapshot-github-deploy.yaml
--- a/.github/workflows/maven-snapshot-github-deploy.yaml
+++ b/.github/workflows/maven-snapshot-github-deploy.yaml
@@ -31,22 +31,22 @@ jobs:
       - name: "Setup xmlstarlet"
         run: |
           sudo apt install -y xmlstarlet
-      - name: "Check that version is SNAPSHOT"
-        shell: bash
-        run: |
-          cd ${GITHUB_WORKSPACE}
-          IS_SNAPSHOT=$(xmlstarlet sel -N x="http://maven.apache.org/POM/4.0.0" -t -v "/x:project/x:properties/x:revision[contains(., '-SNAPSHOT')]" ./pom.xml || echo "")
-          if [[ "${IS_SNAPSHOT}" == "" ]]
-          then
-            echo "❗ The project/properties/revision in the pom.xml has no '-SNAPSHOT' postfix." >> $GITHUB_STEP_SUMMARY
-            echo "❗ Workflow fail. Please add '-SNAPSHOT' to the revision." >> $GITHUB_STEP_SUMMARY
-            echo "❗ The project/properties/revision in the pom.xml has '-SNAPSHOT' postfix."
-            echo "Workflow fail. Please add '-SNAPSHOT' to the revision."
-            exit 1
-          else
-            echo "✅ The project/properties/revision in the pom.xml has '-SNAPSHOT' postfix: ${IS_SNAPSHOT}" >> $GITHUB_STEP_SUMMARY
-            echo "✅ The project/properties/revision in the pom.xml has '-SNAPSHOT' postfix: ${IS_SNAPSHOT}"
-          fi
+#      - name: "Check that version is SNAPSHOT"
+#        shell: bash
+#        run: |
+#          cd ${GITHUB_WORKSPACE}
+#          IS_SNAPSHOT=$(xmlstarlet sel -N x="http://maven.apache.org/POM/4.0.0" -t -v "/x:project/x:properties/x:revision[contains(., '-SNAPSHOT')]" ./pom.xml || echo "")
+#          if [[ "${IS_SNAPSHOT}" == "" ]]
+#          then
+#            echo "❗ The project/properties/revision in the pom.xml has no '-SNAPSHOT' postfix." >> $GITHUB_STEP_SUMMARY
+#            echo "❗ Workflow fail. Please add '-SNAPSHOT' to the revision." >> $GITHUB_STEP_SUMMARY
+#            echo "❗ The project/properties/revision in the pom.xml has '-SNAPSHOT' postfix."
+#            echo "Workflow fail. Please add '-SNAPSHOT' to the revision."
+#            exit 1
+#          else
+#            echo "✅ The project/properties/revision in the pom.xml has '-SNAPSHOT' postfix: ${IS_SNAPSHOT}" >> $GITHUB_STEP_SUMMARY
+#            echo "✅ The project/properties/revision in the pom.xml has '-SNAPSHOT' postfix: ${IS_SNAPSHOT}"
+#          fi
       - name: "Set up JDK"
         uses: actions/setup-java@v4
         with:
